version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build:
      context: .
      target: production
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:postgrespassword@db:5432/mydatabase
      API_VERSION: v1
      NODE_ENV: production
      PORT: 5000
    ports:
      - "5000:5000"
    depends_on:
      - db
    command: >
      sh -c "
        yarn db:migrate && 
        yarn prod:db:seed && 
        yarn start"
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
